# These steps have to run on a windows machine,
# and therefore unfortunately can't be integrated in the regular steps

parameters:
  - name: serviceTreeID
    type: string
    default: 'PLEASE USE YOUR SERVICE TREE ID FOR THE REPO'

jobs:
  - job: Compliance
    displayName: Compliance checks
    pool:
      name: 1ES-Teams-Win2019-Security
    steps:
      - task: UseDotNet@2
        condition: succeededOrFailed()
        displayName: 'Use .NET Core sdk 3.x'
        inputs:
          version: 3.x
          steps:

      - task: skvso.servicetree-build-tasks.servicetree-link-build-task.servicetree-link-build-task@1
        displayName: 'ServiceTree Integration'
        inputs:
          ServiceTreeGateway: 'ServiceTree Gateway'
          Service: ${{ parameters.serviceTreeID }}
          BuildOutputUsage: production

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@3
        condition: succeededOrFailed()
        displayName: 'ðŸ§­ Run Credential Scanner'
        inputs:
          debugMode: false

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-eslint.ESLint@1
        condition: succeededOrFailed()
        displayName: 'ðŸ§­ Run ESLint'

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@3
        displayName: 'ðŸ§­ Publish Guardian Artifacts - All Tools'
        inputs:
          ArtifactType: M365
        condition: succeededOrFailed()

      - task: AssetRetention@3
        displayName: ðŸ§­ Arrow Retention
        inputs:
          ArrowServiceConnection: 'Arrow_domoreexp_Teamspace_PROD'
          AssetGroupName: '$(System.TeamProject)_$(Build.DefinitionName)'
          AssetNumber: '$(Build.BuildId)'
          IsShipped: false
          DropsToRetain: 'CodeAnalysisLogs'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@2
        displayName: 'ðŸ§­ Guardian Break'
        inputs:
          GdnBreakPolicyMinSev: Warning
          GdnBreakAllTools: true
          GdnBreakGdnToolESLint: true
          GdnBreakGdnToolESLintSeverity: Warning
          GdnBreakPolicy: M365
        condition: succeededOrFailed()
